services:
  mysql:
    image: mysql:8.0
    container_name: mysql-space-booking-app-27amo
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: space_booking_db
    ports:
      - "39001:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge